# Generated by Django 5.1.2 on 2025-04-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0002_event_description_event_start_date_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
