# Generated by Django 5.1.2 on 2025-05-01 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0005_remove_event_organizer_organizers_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='event',
        ),
        migrations.RemoveField(
            model_name='organizers',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etms_app.organizers'),
        ),
    ]
