# Generated by Django 5.1.2 on 2025-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0007_alter_event_organizer_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='organizer',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
