# Generated by Django 5.1.2 on 2025-05-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0008_sales_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='ticket',
        ),
    ]
