# Generated by Django 5.1.2 on 2025-05-03 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0009_remove_sales_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendees',
            new_name='Attendee',
        ),
        migrations.RenameModel(
            old_name='Organizers',
            new_name='Organizer',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
