# Generated by Django 5.1.2 on 2025-05-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0010_rename_attendees_attendee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='ticket',
        ),
    ]
