# Generated by Django 5.1.2 on 2025-05-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0011_remove_attendee_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='name',
        ),
        migrations.AddField(
            model_name='attendee',
            name='is_attendee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizer',
            name='is_organizer',
            field=models.BooleanField(default=True),
        ),
    ]
