# Generated by Django 5.1.2 on 2025-05-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0012_remove_attendee_name_attendee_is_attendee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='etms_app.event'),
        ),
    ]
