# Generated by Django 5.1.2 on 2025-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0013_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
