# Generated by Django 5.1.2 on 2025-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0014_remove_sale_organizer_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ManyToManyField(related_name='attendees', to='etms_app.event'),
        ),
    ]
