# Generated by Django 5.1.2 on 2025-05-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0015_remove_attendee_event_attendee_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etms_app.organizer'),
        ),
    ]
