# Generated by Django 5.1.2 on 2025-05-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etms_app', '0016_sale_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='organizer',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
